version: '3'

services:
  config-server:
    build:
      context: ./config-server
    expose: 
      - 8000
    environment:
      - CONFIG_URL=https://github.com/tastycats/gablum-config.git
      - CONFIG_SERVER_PORT=8000

  discovery:
    build:
      context: ./discovery-server
    environment: 
      - CONFIG_SERVER=http://config-server:8000
      - DISCOVERY_PORT=8001
    expose: 
       - 8001
    ports:
      - "8001:8001"
    depends_on: 
      - config-server
    entrypoint: 
      - ./wait
      - config-server:8000
      - -t
      - "60"
      - --
      - java
      - -jar
      - /usr/app/app.jar
  
  gateway:
    build:
      context: ./gateway
    environment: 
      - REGISTRY_URI=http://discovery:8001/eureka
      - CONFIG_SERVER=http://config-server:8000
      - GATEWAY_PORT=80
    expose: 
       - 80
    ports:
      - "80:80"
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "60"
      - --
      - java
      - -jar
      - /usr/app/app.jar
  
  user-api:
    build:
      context: ./user-api
    environment: 
      - REGISTRY_URI=http://discovery:8001/eureka
      - CONFIG_SERVER=http://config-server:8000
      - SERVER_PORT=4000
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "60"
      - --
      - java
      - -jar
      - /usr/app/app.jar
  
  ui:
    build:
      context: ./ui
    environment: 
      - REGISTRY_URI=http://discovery:8001/eureka
      - CONFIG_SERVER=http://config-server:8000
      - SERVER_PORT=4000
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "60"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  auctions:
    build:
      context: ./auction/auctions
    environment: 
      - REGISTRY_URI=http://discovery:8001/eureka
      - CONFIG_SERVER=http://config-server:8000
      - SERVER_PORT=4000
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "60"
      - --
      - java
      - -jar
      - /usr/app/app.jar

  bid:
    build:
      context: ./auction/bid
    environment: 
      - REGISTRY_URI=http://discovery:8001/eureka
      - CONFIG_SERVER=http://config-server:8000
      - SERVER_PORT=4000
    depends_on: 
      - discovery
    entrypoint: 
      - ./wait
      - discovery:8001
      - -t
      - "60"
      - --
      - java
      - -jar
      - /usr/app/app.jar